version: "3.8"

services:
  angular:
    build:
      dockerfile: Dockerfile
    restart: "no"
    volumes:
      - ..:/workspace:cached # Your code
      - ~/.ssh:/home/node/.ssh:cached # Your SSH keys if you use a custom git+ssh repo
    command: /bin/sh -c "while sleep 1000; do :; done" # Keep container running on start to let some time to VSCode to open a shell inside before it closes
